title: Breathing Code
kramdown: redcarpet
redcarpet:
  extensions: [with_toc_data, strikethrough, superscript, footnotes]
highlighter: pygments
sass:
  style: compressed
email: organizers@breathing-code.de
